#!/usr/bin/env bash
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Fetches the OpenAPI document from a running application and writes it into schemas/.
#
# The document is generated by the application from its own ToolRegistry, so it cannot drift from
# the code. CDK needs it on disk at synth time, which is the one genuinely awkward seam in this
# design: the artefact is produced at runtime but consumed at deploy time. Run this as a build step
# (or in CI, against a deployed instance) rather than editing the file by hand.
#
# Usage:
#   ./scripts/fetch-schema.sh orderapp https://orders.internal.example.com "$SHARED_SECRET"

set -euo pipefail

TARGET_NAME="${1:?usage: fetch-schema.sh <target-name> <base-url> <shared-secret>}"
BASE_URL="${2:?usage: fetch-schema.sh <target-name> <base-url> <shared-secret>}"
SHARED_SECRET="${3:?usage: fetch-schema.sh <target-name> <base-url> <shared-secret>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${SCRIPT_DIR}/../schemas"
OUTPUT_FILE="${OUTPUT_DIR}/${TARGET_NAME}.openapi.json"

mkdir -p "${OUTPUT_DIR}"

echo "Fetching ${BASE_URL%/}/_mcp/openapi.json"

# --fail so an HTML error page never lands in the schema file. A 404 here usually means
# mcp:enabled is not set; a 401 means the secret does not match.
curl --fail --silent --show-error \
  --header "X-Mcp-Key: ${SHARED_SECRET}" \
  "${BASE_URL%/}/_mcp/openapi.json" \
  -o "${OUTPUT_FILE}.tmp"

# Reject anything that is not parseable JSON before it can break synthesis.
python3 -c "import json,sys; json.load(open(sys.argv[1]))" "${OUTPUT_FILE}.tmp"

mv "${OUTPUT_FILE}.tmp" "${OUTPUT_FILE}"
echo "Wrote ${OUTPUT_FILE}"

# Surface the application's own view of AgentCore compatibility. Synthesis checks the document
# again with the target name in hand, but this catches problems earlier and more cheaply.
echo
echo "Application health:"
curl --fail --silent --show-error \
  --header "X-Mcp-Key: ${SHARED_SECRET}" \
  "${BASE_URL%/}/_mcp/health"
echo
